# Generated by Django 4.1.7 on 2023-02-22 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Сategories",
        ),
    ]
