# Generated by Django 4.1.7 on 2023-02-22 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_rename_category_сategories"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Сategories",
            new_name="Category",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("name",),
                "verbose_name": "menu item",
                "verbose_name_plural": "menu items",
            },
        ),
    ]
