# Generated by Django 4.1.7 on 2023-02-22 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_rename_сategories_category_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("slug",),
                "verbose_name": "menu item",
                "verbose_name_plural": "menu items",
            },
        ),
        migrations.RemoveField(
            model_name="item",
            name="name",
        ),
    ]
