# Generated by Django 4.1.7 on 2023-02-22 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_alter_item_options_remove_item_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="parents",
            new_name="parent",
        ),
    ]
