# Generated by Django 4.1.7 on 2023-02-22 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0005_rename_parents_item_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("id",),
                "verbose_name": "menu item",
                "verbose_name_plural": "menu items",
            },
        ),
    ]
